
[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Ï€-DOC"
authors = [{name = "Paolo Bianchini", email = "paolo.bianchini@astro.unistra.fr"}]
dynamic = ["version", "description"]
